name: Build and Publish Docker Image

on:
  workflow_dispatch:

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract version from package.json
      id: extract-version
      run: |
        if ! version=$(jq -r .version package.json); then
          echo "Error: Failed to extract version from package.json" >&2
          exit 1
        fi
        echo "version=$version" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ vars.DOCKER_USERNAME }}/clickup-mcp-server:${{ env.version }}
          ${{ vars.DOCKER_USERNAME }}/clickup-mcp-server:latest

    - name: Create GitHub Release
      run: |
        gh release create ${{ env.version }} --title "Release ${{ env.version }}" --notes "Docker image published to Docker Hub.\n\n[View on Docker Hub](https://hub.docker.com/r/${{ vars.DOCKER_USERNAME }}/clickup-mcp-server)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
